### ISSUE TITLE
Powermail V9

### ISSUE THREAD

**Issue by timapler** [thomasrawiel/powermailcaptcha#2]
Heyho,

is there a reason why powermailcaptcha is only available for powermail v8 and v10 but not for v9. Right now we're using v9 because it runs under TYPO3 11.5 and still includes parsley as client validation, which v10 doesn't anymore.

Tim

**Comment by thomasrawiel** [comment]
Hi Tim,

no there's no specific reason.

I just haven't tested it with v9 because we skipped that version in all our projects. 
Maybe I just forgot to add it to the composer.json file.

I just pushed version [1.0.3](https://github.com/thomasrawiel/powermailcaptcha/compare/1.0.2...1.0.3). 
Please test and report back if everything works. 

Thanks!
