### ISSUE TITLE
[FEAT] 1.x is missing the prosopo partial

### ISSUE THREAD

**Issue by Make66** [thomasrawiel/powermailcaptcha#26]
please add /Resources/Private/Partials/Captcha/Procaptcha.html to tag 1.6.x

**Comment by thomasrawiel** [comment]
That was added in version 2.1
If you have powermail version > 12 you can update to powermailcaptcha ^2.1

For 1.6 I created a new branch. composer require `main-1-6.xdev` or ^1.7


Please note, that prosopo is still untested, since the PR author hasn't given any feedback, yet.
Could you report back if it works as expected?
Thanks
