### ISSUE TITLE
Add language awareness (i18n support)?

### ISSUE THREAD

**Issue by sypets** [thomasrawiel/powermailcaptcha#6]
I would like the friendlycaptcha variant to use the language of the TYPO3 page. 

This issue is still open, but it seems to be working already: https://github.com/FriendlyCaptcha/friendly-challenge/issues/9

If I change it in the Fluid 

```
- <div class="frc-captcha" data-sitekey="{settings.powermailcaptcha.sitekey}"></div>
+ <div class="frc-captcha" data-sitekey="{settings.powermailcaptcha.sitekey}" data-lang="de"></div>
```

the captcha text will be in German.

Of course, this should be done dynamically, based on the language of the page.

![image](https://github.com/thomasrawiel/powermailcaptcha/assets/13206455/8ec3c546-91fa-4b12-9312-b6c14c0157ed)

**Comment by thomasrawiel** [comment]
I have added an option to force the captcha's language to the current site language, instead of detecting the language by itself (html tag, browser-language). 
This feature assumes you have a correct Two Letter ISO Code [iso-639-1] set in your Siteconfig.

Please checkout [feature/website-language](https://packagist.org/packages/traw/powermailcaptcha#dev-feature/website-language) and test this with your setup.

I have tested it with google recaptcha.

Please note: I had to add Partials/Form/Page.html to be able to add my language variable to the Captcha Field
`<f:render partial="Form/Field/{vh:String.Upper(string:field.type)}" arguments="{field:field, languageIso:languageIso}"/>`
